name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Basic repo checks
        run: |
          echo "Running basic checks..."
          test -f README.md
          echo "OK"
